dist: trusty
sudo: false

language: java

services: mongodb

jdk:
  - oraclejdk8

notifications:
  email:
    recipients:
      - mhahn.dev@gmail.com
    on_success: change
    on_failure: always

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew clean build
  - ./gradlew clean integrationTest
