version: '2'
services:
  trade-mongodb:
    build:
      context: .
      dockerfile: Dockerfile-db
    image: trade-core:mongodb
    container_name: "trade-core"
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/db-data/db
      - MONGO_LOG_DIR=/db-dev/null
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

#
# Build and run as daemon:
#
#   docker-compose build
#
#   docker-compose up -d
#
# The containers are running in the background and remain active until they are explicitly stopped by running:
#
#   docker-compose stop
#
# For further details on Docker compose see https://docs.docker.com/compose/overview/
#